"""movie update

Revision ID: 094682fc012f
Revises: d31af9aa12b3
Create Date: 2025-05-29 23:20:31.086587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094682fc012f'
down_revision: Union[str, None] = 'd31af9aa12b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('movie_cast_actor_id_fkey', 'movie_cast', type_='foreignkey')
    op.drop_table('movie_cast')
    op.drop_table('actors')
    op.add_column('movies', sa.Column('cast', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('movies', 'cast')
    op.create_table('movie_cast',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name='movie_cast_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='movie_cast_movie_id_fkey'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id', name='movie_cast_pkey')
    )
    op.create_table('actors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='actors_pkey')
    )
    op.create_index('ix_actors_id', 'actors', ['id'], unique=False)
    # ### end Alembic commands ###
