"""update tickets table

Revision ID: 0f8e99b09ba0
Revises: 48517742ea4d
Create Date: 2025-08-04 17:02:50.979441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8e99b09ba0'
down_revision: Union[str, None] = '48517742ea4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('price', sa.Float(), nullable=True, server_default='0.0'))
    op.alter_column('tickets', 'price', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'price')
    # ### end Alembic commands ###
