"""update schedules table

Revision ID: 3f8e5d5065bd
Revises: 6687ab70bf1b
Create Date: 2025-08-12 15:07:19.141078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8e5d5065bd'
down_revision: Union[str, None] = '6687ab70bf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('movie_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'movie_type')
    # ### end Alembic commands ###
