"""add ticket_prices table

Revision ID: 5f75f4e0778f
Revises: ab7603a25057
Create Date: 2025-08-04 00:39:01.577159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f75f4e0778f'
down_revision: Union[str, None] = 'ab7603a25057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('cheap_thursday', sa.String(), nullable=False),
    sa.Column('three_days_before', sa.String(), nullable=False),
    sa.Column('two_days_before', sa.String(), nullable=False),
    sa.Column('one_day_before', sa.String(), nullable=False),
    sa.Column('same_day', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_prices_id'), 'ticket_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_prices_id'), table_name='ticket_prices')
    op.drop_table('ticket_prices')
    # ### end Alembic commands ###
