"""update tickets table

Revision ID: 6687ab70bf1b
Revises: d550f4a8c209
Create Date: 2025-08-09 00:49:15.349365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6687ab70bf1b'
down_revision: Union[str, None] = 'd550f4a8c209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_seats', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_seats', 'type')
    # ### end Alembic commands ###
