"""update tickets table

Revision ID: 903086e5c7f2
Revises: d43db57c3659
Create Date: 2025-08-09 00:25:58.843190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903086e5c7f2'
down_revision: Union[str, None] = 'd43db57c3659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_prices', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_prices', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
