"""update tickets table

Revision ID: aa6efabd38a7
Revises: 3f8e5d5065bd
Create Date: 2025-08-22 17:08:02.133488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6efabd38a7'
down_revision: Union[str, None] = '3f8e5d5065bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_seats', sa.Column('row_index', sa.Integer(), nullable=True))
    op.add_column('ticket_seats', sa.Column('col_index', sa.Integer(), nullable=True))
    op.add_column('ticket_seats', sa.Column('row_label', sa.String(), nullable=True))
    op.add_column('ticket_seats', sa.Column('seat_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_seats', 'seat_number')
    op.drop_column('ticket_seats', 'row_label')
    op.drop_column('ticket_seats', 'col_index')
    op.drop_column('ticket_seats', 'row_index')
    # ### end Alembic commands ###
