"""update tickets table

Revision ID: d43db57c3659
Revises: 0f8e99b09ba0
Create Date: 2025-08-08 23:00:29.572891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43db57c3659'
down_revision: Union[str, None] = '0f8e99b09ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_prices', sa.Column('day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_prices', 'day')
    # ### end Alembic commands ###
