"""update tickets table

Revision ID: d550f4a8c209
Revises: 903086e5c7f2
Create Date: 2025-08-09 00:35:18.688991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd550f4a8c209'
down_revision: Union[str, None] = '903086e5c7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_seats_id'), 'ticket_seats', ['id'], unique=False)
    op.add_column('tickets', sa.Column('total_price', sa.Float(), nullable=False))
    op.drop_column('tickets', 'seat')
    op.drop_column('tickets', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('seat', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'total_price')
    op.drop_index(op.f('ix_ticket_seats_id'), table_name='ticket_seats')
    op.drop_table('ticket_seats')
    # ### end Alembic commands ###
